import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Hero from "@/Components/Hero";
import Showcase from "@/Components/Showcase";
import Blogs from "@/Components/Blogs";
import Benefits from "@/Components/Benefits";
import Details from "@/Components/Details";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        <Hero/>
        <Showcase/>
        <Blogs/>
        <Benefits/>
        <Details/>
        {children}
        </body>
    </html>
  );
}
